# Generated by Django 5.0 on 2026-07-31 11:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username_snapshot', models.CharField(blank=True, default='', max_length=128, verbose_name='İstifadəçi adı (snapshot)')),
                ('action_type', models.CharField(choices=[('login', 'Daxil oldu'), ('logout', 'Çıxış etdi'), ('viewed', 'Baxdı'), ('created', 'Yaratdı'), ('updated', 'Dəyişiklik etdi'), ('deleted', 'Sildi'), ('exported', 'İxrac etdi'), ('other', 'Digər')], max_length=20, verbose_name='Əməliyyat növü')),
                ('module_code', models.CharField(blank=True, default='', max_length=100, verbose_name='Modul kodu')),
                ('module_title', models.CharField(blank=True, default='', max_length=150, verbose_name='Modul adı')),
                ('sub_module_title', models.CharField(blank=True, default='', max_length=150, verbose_name='Alt modul adı')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Təsvir')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='Obyekt')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Dəyişikliklər')),
                ('request_method', models.CharField(blank=True, default='', max_length=10, verbose_name='HTTP metodu')),
                ('request_path', models.CharField(blank=True, default='', max_length=500, verbose_name='URL')),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Status kodu')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP ünvanı')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='Brauzer/cihaz')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tarix/Vaxt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Sayt loqu',
                'verbose_name_plural': 'Sayt loqları',
                'ordering': ('-timestamp',),
                'indexes': [models.Index(fields=['user', 'timestamp'], name='activity_lo_user_id_8d9f3d_idx'), models.Index(fields=['module_code', 'timestamp'], name='activity_lo_module__99863b_idx'), models.Index(fields=['action_type', 'timestamp'], name='activity_lo_action__808881_idx')],
            },
        ),
    ]
