# Generated by Django 5.0 on 2026-07-27 09:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='dəyişdirilmə tarixi')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('path', models.CharField(max_length=255, verbose_name='Path (URL)')),
                ('permission', models.CharField(help_text='Məsələn: risk.view_risk', max_length=150, verbose_name='Permission')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
            ],
            options={
                'verbose_name': 'Modul',
                'verbose_name_plural': 'Modullar',
                'ordering': ['order'],
            },
        ),
    ]
