# Generated by Django 5.0 on 2026-07-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='elevated_path',
            field=models.CharField(blank=True, help_text='Məsələn: /risk (redaktə edə bilənlər üçün)', max_length=255, null=True, verbose_name='Yüksək səlahiyyət path-i (opsional)'),
        ),
        migrations.AddField(
            model_name='module',
            name='elevated_permission',
            field=models.CharField(blank=True, help_text="Boş buraxsanız, hər kəs 'path' sahəsinə yönləndirilir. Doldursanız, bu permission-lardan biri olanlar 'elevated_path'-a gedir.", max_length=150, null=True, verbose_name='Əlavə/Redaktə permission-u (opsional)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='path',
            field=models.CharField(max_length=255, verbose_name='Əsas path (baxış üçün)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='permission',
            field=models.CharField(help_text='Məsələn: risk.view_risk', max_length=150, verbose_name='Görünmə üçün minimum permission'),
        ),
    ]
