# Generated by Django 5.0 on 2026-07-28 06:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_module_elevated_path_module_elevated_permission_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='dəyişdirilmə tarixi')),
                ('code', models.CharField(choices=[('PENDING', 'Gözləmədə'), ('COMPLETED', 'Bitib'), ('CANCELED', 'Ləğv edilib')], default='PENDING', max_length=128, verbose_name='Statusun kodu')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='Statusun adı')),
                ('color', models.CharField(blank=True, max_length=128, null=True, verbose_name='Statusun rəngi')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Statuslar',
            },
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'verbose_name': 'Modul', 'verbose_name_plural': 'Modullar'},
        ),
        migrations.RemoveField(
            model_name='module',
            name='elevated_path',
        ),
        migrations.RemoveField(
            model_name='module',
            name='elevated_permission',
        ),
        migrations.RemoveField(
            model_name='module',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='module',
            name='order',
        ),
        migrations.RemoveField(
            model_name='module',
            name='path',
        ),
        migrations.RemoveField(
            model_name='module',
            name='permission',
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Modul təsviri'),
        ),
        migrations.AddField(
            model_name='module',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='module_images/%Y/%m/%d', verbose_name='Modul ikonu'),
        ),
        migrations.AddField(
            model_name='module',
            name='permitted_users',
            field=models.ManyToManyField(blank=True, related_name='modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='url_endpoint',
            field=models.CharField(default=1, max_length=120, verbose_name='Url linki'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Modul adı'),
        ),
        migrations.CreateModel(
            name='SubModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='dəyişdirilmə tarixi')),
                ('title', models.CharField(max_length=120, verbose_name='Alt modul adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Alt modul təsviri')),
                ('url_endpoint', models.CharField(max_length=120, verbose_name='Url linki')),
                ('image', models.ImageField(blank=True, null=True, upload_to='sub_module_images/%Y/%m/%d', verbose_name='Alt modul ikonu')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_modules', to='core.module', verbose_name='Əsas modul')),
                ('permitted_users', models.ManyToManyField(blank=True, related_name='sub_modules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alt Modul',
                'verbose_name_plural': 'Alt Modullar',
                'unique_together': {('module', 'title')},
            },
        ),
    ]
