# Generated by Django 5.0 on 2026-07-28 07:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_organization_user_organization'),
        ('core', '0003_status_alter_module_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='permitted_organizations',
            field=models.ManyToManyField(blank=True, related_name='modules', to='authentication.organization', verbose_name='İcazəli qurumlar'),
        ),
        migrations.AddField(
            model_name='submodule',
            name='permitted_organizations',
            field=models.ManyToManyField(blank=True, related_name='sub_modules', to='authentication.organization', verbose_name='İcazəli qurumlar'),
        ),
        migrations.AlterField(
            model_name='module',
            name='permitted_users',
            field=models.ManyToManyField(blank=True, related_name='modules', to=settings.AUTH_USER_MODEL, verbose_name='Fərdi icazəli istifadəçilər'),
        ),
        migrations.AlterField(
            model_name='submodule',
            name='permitted_users',
            field=models.ManyToManyField(blank=True, related_name='sub_modules', to=settings.AUTH_USER_MODEL, verbose_name='Fərdi icazəli istifadəçilər'),
        ),
    ]
