# Generated by Django 5.0 on 2026-07-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_organization_user_organization'),
        ('core', '0004_module_permitted_organizations_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='permitted_organizations',
            field=models.ManyToManyField(blank=True, help_text="Bu modulun hansı qurum(lar) üçün nəzərdə tutulduğunu göstərir. DİQQƏT: bu sahə tək başına heç bir user-ə giriş vermir — qurumun bütün işçilərinə avtomatik açılmır. Real giriş yalnız 'Fərdi icazəli istifadəçilər' (permitted_users) sahəsi ilə verilir; burada seçilən qurum(lar) yalnız o sahəyə hansı user-lərin əlavə oluna biləcəyini məhdudlaşdırır (başqa qurumun işçisi əlavə edilə bilməz).", related_name='modules', to='authentication.organization', verbose_name='Əlaqəli qurumlar (əhatə dairəsi)'),
        ),
        migrations.AlterField(
            model_name='submodule',
            name='permitted_organizations',
            field=models.ManyToManyField(blank=True, help_text="Yalnız hansı qurum(lar)ın işçilərinin 'Fərdi icazəli istifadəçilər' sahəsinə əlavə oluna biləcəyini məhdudlaşdırır. Tək başına giriş vermir.", related_name='sub_modules', to='authentication.organization', verbose_name='Əlaqəli qurumlar (əhatə dairəsi)'),
        ),
    ]
