# Generated by Django 5.0 on 2026-07-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_module_permitted_organizations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='code',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submodule',
            name='code',
            field=models.SlugField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
