# Generated by Django 5.0 on 2026-07-30 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_is_org_admin'),
        ('core', '0006_module_code_submodule_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='permitted_organizations',
            field=models.ManyToManyField(blank=True, help_text="Bu modulun hansı qurum(lar) üçün nəzərdə tutulduğunu göstərir. Bu sahədəki qurumun ADMİNİ (is_org_admin) modula AVTOMATİK giriş əldə edir. Qurumun adi işçiləri isə avtomatik giriş almır - onlara giriş yalnız 'Fərdi icazəli istifadəçilər' (permitted_users) sahəsi ilə (və ya qurum admininin admin panelindən) verilir.", related_name='modules', to='authentication.organization', verbose_name='Əlaqəli qurumlar (əhatə dairəsi)'),
        ),
        migrations.AlterField(
            model_name='submodule',
            name='permitted_organizations',
            field=models.ManyToManyField(blank=True, help_text="Bu sahədəki qurumun ADMİNİ (is_org_admin) alt-modula AVTOMATİK giriş əldə edir (əsas modula da girişi olduğu halda). Qurumun adi işçiləri isə avtomatik giriş almır - onlara giriş yalnız 'Fərdi icazəli istifadəçilər' (permitted_users) sahəsi ilə (və ya qurum admininin admin panelindən) verilir.", related_name='sub_modules', to='authentication.organization', verbose_name='Əlaqəli qurumlar (əhatə dairəsi)'),
        ),
    ]
