# Generated by Django 5.0 on 2026-09-15 06:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_module_permitted_organizations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='admin_users',
            field=models.ManyToManyField(blank=True, help_text="Bu modul daxilində məzmun əlavə etmək/redaktə etmək səlahiyyəti olan istifadəçilər. Modul admini avtomatik olaraq modula giriş də əldə edir (permitted_users-a əlavə edilməsinə ehtiyac yoxdur). Konkret app-larda bu, `core.permissions.is_module_admin(user, module_code)` vasitəsilə yoxlanılıb 'add'/'change' səlahiyyəti kimi tətbiq oluna bilər.", related_name='administered_modules', to=settings.AUTH_USER_MODEL, verbose_name='Modul adminləri (əlavə/redaktə icazəli)'),
        ),
    ]
