# Generated by Django 5.0 on 2026-09-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_module_admin_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Aktiv edilsə, bu modul VƏ onun bütün alt modulları qurum/istifadəçi icazələrindən asılı olmayaraq bütün autentifikasiya olunmuş istifadəçilərə görünür və açıq olur.', verbose_name='Hər kəsə açıq'),
        ),
    ]
