# Generated by Django 5.0 on 2026-10-02 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_module_is_public"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submodule",
            name="admin_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Yalnız BU alt modul daxilində idarəetmə (əlavə/redaktə) səlahiyyəti olan istifadəçilər. Eyni modulun müxtəlif alt modullarının adminləri fərqli şəxslər ola bilər (məs. 'Təlim materialları' və 'Təlim statistikası'). Əsas modulun admini (Module.admin_users) bütün alt modullarda avtomatik admin sayılır. Bax: core.permissions.is_sub_module_admin.",
                related_name="administered_sub_modules",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Alt modul adminləri",
            ),
        ),
    ]
