# Generated by Django 5.0 on 2026-10-06 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_rename_logs_module_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="submodule",
            name="is_restricted",
            field=models.BooleanField(
                default=False,
                help_text="Əsas modul hər kəsə açıq olsa belə, bu alt modula yalnız icazə verilmiş şəxslər daxil ola bilər (məs. Təlimlər hamıya açıqdır, Təlim statistikası isə yox).",
                verbose_name="Məhdud alt modul",
            ),
        ),
    ]
