# Generated by Django 5.0 on 2026-08-06 11:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0009_role_is_manager_role_user_is_apparatus_head_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='dəyişdirilmə tarixi')),
                ('date', models.DateField(verbose_name='Tarix')),
                ('start_time', models.TimeField(verbose_name='Başlanğıc saatı')),
                ('end_time', models.TimeField(verbose_name='Bitmə saatı')),
                ('location', models.CharField(max_length=255, verbose_name='Yer')),
                ('reason', models.TextField(blank=True, default='', verbose_name='Səbəb / qeyd')),
                ('status', models.CharField(choices=[('pending', 'Gözləmədə'), ('approved', 'Təsdiqlənib'), ('rejected', 'Rədd edilib')], default='pending', max_length=16, verbose_name='Status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Baxılma tarixi')),
                ('review_comment', models.TextField(blank=True, default='', verbose_name='Rəy / qeyd')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_permissions', to='authentication.department', verbose_name='Departament')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_permissions', to='authentication.organization', verbose_name='Qurum')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Təsdiqləyən / Rədd edən')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_permissions', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'İcazə',
                'verbose_name_plural': 'İcazələr',
                'ordering': ['-created_at'],
            },
        ),
    ]
