# Generated by Django 5.0 on 2026-08-07 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_permissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepermission',
            name='department_review_comment',
            field=models.TextField(blank=True, default='', verbose_name='Şöbə müdirinin rəyi'),
        ),
        migrations.AddField(
            model_name='attendancepermission',
            name='department_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Şöbə müdirinin baxma tarixi'),
        ),
        migrations.AddField(
            model_name='attendancepermission',
            name='department_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_reviewed_attendance_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Şöbə müdiri (baxan)'),
        ),
        migrations.AlterField(
            model_name='attendancepermission',
            name='review_comment',
            field=models.TextField(blank=True, default='', verbose_name='Son rəy / qeyd'),
        ),
        migrations.AlterField(
            model_name='attendancepermission',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Son baxılma tarixi'),
        ),
        migrations.AlterField(
            model_name='attendancepermission',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attendance_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Son qərarı verən'),
        ),
        migrations.AlterField(
            model_name='attendancepermission',
            name='status',
            field=models.CharField(choices=[('pending', 'Gözləmədə'), ('awaiting_apparatus', 'Aparat rəhbərinin təsdiqini gözləyir'), ('approved', 'Təsdiqlənib'), ('rejected', 'Rədd edilib')], default='pending', max_length=32, verbose_name='Status'),
        ),
    ]
