# Generated by Django 5.0 on 2026-08-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_permissions', '0002_attendancepermission_department_review_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancepermission',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Yer'),
        ),
    ]
