# Generated by Django 5.0 on 2026-08-25 08:07

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_permissions', '0003_alter_attendancepermission_location'),
        ('authentication', '0010_remove_role_gpa_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePermissionDepartmentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='dəyişdirilmə tarixi')),
                ('manager_enabled', models.BooleanField(default=True, verbose_name='Şöbə müdiri aktivdir')),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_permission_config', to='authentication.department', verbose_name='Departament')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_permission_department_configs', to='authentication.organization', verbose_name='Qurum')),
                ('replacement_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_permission_replacement_configs', to=settings.AUTH_USER_MODEL, verbose_name='Əvəzləyici şəxs')),
            ],
            options={
                'verbose_name': 'Departament icazə konfiqurasiyası',
                'verbose_name_plural': 'Departament icazə konfiqurasiyaları',
            },
        ),
        migrations.CreateModel(
            name='AttendancePermissionOrganizationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='dəyişdirilmə tarixi')),
                ('apparatus_head_enabled', models.BooleanField(default=True, verbose_name='Aparat rəhbəri aktivdir')),
                ('apparatus_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_apparatus_head_configs', to=settings.AUTH_USER_MODEL, verbose_name='Aparat rəhbəri')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_permission_config', to='authentication.organization', verbose_name='Qurum')),
            ],
            options={
                'verbose_name': 'İcazə konfiqurasiyası',
                'verbose_name_plural': 'İcazə konfiqurasiyaları',
            },
        ),
        migrations.AddConstraint(
            model_name='attendancepermissiondepartmentconfig',
            constraint=models.UniqueConstraint(fields=('organization', 'department'), name='unique_attendance_permission_department_config'),
        ),
    ]
