# Generated by Django 5.0 on 2026-09-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_permissions', '0004_attendancepermissiondepartmentconfig_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepermissiondepartmentconfig',
            name='no_manager_fallback',
            field=models.CharField(choices=[('replacement', 'Əvəzləyici şəxs (1-ci mərhələdə baxır)'), ('apparatus', 'Birbaşa Aparat rəhbəri (2-ci/son mərhələ)')], default='replacement', help_text='Şöbə müdiri aktiv deyilsə (manager_enabled=False), sorğu kimə göndərilsin: əvəzləyici şəxsə, yoxsa birbaşa Aparat rəhbərinə (1-ci mərhələ tamamilə keçilərək).', max_length=16, verbose_name='Şöbə müdiri yoxdursa'),
        ),
    ]
