# Generated by Django 5.0 on 2026-09-16 06:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_permissions', '0005_attendancepermissiondepartmentconfig_no_manager_fallback'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='dəyişdirilmə tarixi')),
                ('start_date', models.DateField(verbose_name='Başlama tarixi')),
                ('end_date', models.DateField(verbose_name='Bitmə tarixi')),
                ('note', models.CharField(blank=True, default='', max_length=255, verbose_name='Qeyd')),
                ('is_cancelled', models.BooleanField(default=False, help_text='Məzuniyyət vaxtından əvvəl bitirilibsə işarələnir.', verbose_name='Ləğv edilib')),
                ('replacement_user', models.ForeignKey(help_text='Məzuniyyət dövründə işləri həll edəcək şəxs.', on_delete=django.db.models.deletion.CASCADE, related_name='leave_delegations', to=settings.AUTH_USER_MODEL, verbose_name='Əvəzləyici şəxs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_periods', to=settings.AUTH_USER_MODEL, verbose_name='Əməkdaş')),
            ],
            options={
                'verbose_name': 'Məzuniyyət dövrü',
                'verbose_name_plural': 'Məzuniyyət dövrləri',
                'ordering': ('-start_date',),
            },
        ),
        migrations.AddConstraint(
            model_name='leaveperiod',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gte', models.F('start_date'))), name='leave_period_end_after_start'),
        ),
    ]
