# Generated by Django 5.0 on 2026-10-06 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "attendance_permissions",
            "0006_leaveperiod_leaveperiod_leave_period_end_after_start",
        ),
        ("authentication", "0014_sobe_struktur_bolme_adlari"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="attendancepermissiondepartmentconfig",
            options={
                "verbose_name": "Şöbə icazə konfiqurasiyası",
                "verbose_name_plural": "Şöbə icazə konfiqurasiyaları",
            },
        ),
        migrations.AlterField(
            model_name="attendancepermission",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="attendance_permissions",
                to="authentication.department",
                verbose_name="Şöbə",
            ),
        ),
        migrations.AlterField(
            model_name="attendancepermissiondepartmentconfig",
            name="department",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attendance_permission_config",
                to="authentication.department",
                verbose_name="Şöbə",
            ),
        ),
    ]
