# Generated by Django 5.0 on 2026-10-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance_permissions", "0007_sobe_struktur_bolme_adlari"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancepermission",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Gözləmədə"),
                    ("awaiting_apparatus", "Aparat rəhbərinin təsdiqini gözləyir"),
                    ("approved", "Təsdiqlənib"),
                    ("rejected", "İmtina edilib"),
                ],
                default="pending",
                max_length=32,
                verbose_name="Status",
            ),
        ),
    ]
