# Generated by Django 5.0 on 2026-07-15 12:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255, verbose_name='Təyinat')),
                ('legal_basis', models.TextField(blank=True, default='', verbose_name='Hüquqi əsas')),
                ('international_framework', models.TextField(blank=True, default='', verbose_name='Beynəlxalq çərçivələr / Çərçivə istinadı')),
                ('national_legal_reference', models.TextField(blank=True, default='', verbose_name='Milli hüquqi istinad')),
                ('asset_value', models.PositiveSmallIntegerField(verbose_name='Aktivin dəyəri (H)')),
                ('probability', models.PositiveSmallIntegerField(verbose_name='Ehtimal (M)')),
                ('impact', models.PositiveSmallIntegerField(verbose_name='Təsir (N)')),
                ('risk_degree', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Risk dərəcəsi (P)')),
                ('risk_level', models.CharField(choices=[('critical', 'Kritik'), ('high', 'Yüksək'), ('medium', 'Orta'), ('low', 'Aşağı')], default='low', editable=False, max_length=10, verbose_name='Risk səviyyəsi')),
                ('treatment_option', models.CharField(choices=[('prevention', 'Qarşısının alınması'), ('mitigation', 'Təsirin azaldılması'), ('transfer', 'Ötürülmə'), ('acceptance', 'Qəbul')], max_length=20, verbose_name='Emal variantı (Q)')),
                ('residual_risk', models.TextField(blank=True, default='', verbose_name='Qalıq risk (T)')),
                ('update_frequency', models.CharField(blank=True, default='', max_length=255, verbose_name='Yenilənmə tarixi/tezliyi')),
                ('incident_notification_notes', models.TextField(blank=True, default='', verbose_name='İnsident bildirişi qeydləri')),
                ('standard_references', models.TextField(blank=True, default='', verbose_name='Standartlara istinadlar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son dəyişiklik tarixi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_risks', to=settings.AUTH_USER_MODEL, verbose_name='Riski yaradan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_risks', to=settings.AUTH_USER_MODEL, verbose_name='Son dəyişikliyi edən')),
            ],
            options={
                'verbose_name': 'Risk',
                'verbose_name_plural': 'Risklər',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='RiskLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_id_ref', models.PositiveIntegerField(verbose_name='Risk ID')),
                ('risk_snapshot', models.JSONField(blank=True, null=True, verbose_name='Silinmə anındakı tam surət')),
                ('action_type', models.CharField(choices=[('created', 'Yaradıldı'), ('updated', 'Redaktə edildi'), ('deleted', 'Silindi')], max_length=20, verbose_name='Əməliyyat növü')),
                ('field_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Dəyişdirilən sahə')),
                ('old_value', models.TextField(blank=True, null=True, verbose_name='Köhnə dəyər')),
                ('new_value', models.TextField(blank=True, null=True, verbose_name='Yeni dəyər')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Tarix/Vaxt')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Loq qeydi',
                'verbose_name_plural': 'Loq qeydləri',
                'ordering': ('-timestamp',),
            },
        ),
    ]
