# Generated by Django 5.0 on 2026-07-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risklog',
            name='changes',
            field=models.JSONField(blank=True, null=True, verbose_name='Dəyişikliklər'),
        ),
        migrations.AddField(
            model_name='risklog',
            name='risk_designation',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Risk adı (snapshot)'),
        ),
    ]
