# Generated by Django 5.0 on 2026-07-17 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0002_risklog_changes_risklog_risk_designation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risklog',
            name='field_name',
        ),
        migrations.RemoveField(
            model_name='risklog',
            name='new_value',
        ),
        migrations.RemoveField(
            model_name='risklog',
            name='old_value',
        ),
        migrations.AddField(
            model_name='risklog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP ünvanı'),
        ),
        migrations.AddField(
            model_name='risklog',
            name='risk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='risk.risk', verbose_name='Risk'),
        ),
        migrations.AddField(
            model_name='risklog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Brauzer/cihaz'),
        ),
        migrations.AddField(
            model_name='risklog',
            name='user_username_snapshot',
            field=models.CharField(blank=True, default='', max_length=128, verbose_name='İstifadəçi adı (snapshot)'),
        ),
        migrations.AlterField(
            model_name='risklog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Tarix/Vaxt'),
        ),
        migrations.AddIndex(
            model_name='risklog',
            index=models.Index(fields=['risk_id_ref', 'timestamp'], name='risk_risklo_risk_id_f54dd1_idx'),
        ),
        migrations.AddIndex(
            model_name='risklog',
            index=models.Index(fields=['user', 'timestamp'], name='risk_risklo_user_id_5ec01d_idx'),
        ),
    ]
