# Generated by Django 5.0 on 2026-07-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0003_remove_risklog_field_name_remove_risklog_new_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risklog',
            name='action_type',
            field=models.CharField(choices=[('created', 'Yaradıldı'), ('updated', 'Redaktə edildi'), ('deleted', 'Silindi'), ('exported', 'Excel-ə ixrac edildi')], max_length=20, verbose_name='Əməliyyat növü'),
        ),
    ]
