# Generated by Django 5.0 on 2026-07-27 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0004_alter_risklog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risklog',
            name='action_type',
            field=models.CharField(choices=[('created', 'Yaradıldı'), ('updated', 'Redaktə edildi'), ('deleted', 'Silindi'), ('exported', 'Excel-ə ixrac edildi'), ('viewed', 'Səhifəyə/modula baxıldı')], max_length=20, verbose_name='Əməliyyat növü'),
        ),
    ]
