# Generated by Django 5.0 on 2026-07-28 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_organization_user_organization'),
        ('risk', '0006_alter_risklog_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='authentication.organization', verbose_name='Qurum'),
        ),
        migrations.AddField(
            model_name='risklog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='risk_logs', to='authentication.organization', verbose_name='Qurum'),
        ),
    ]
