# Generated by Django 5.0 on 2026-08-03 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('risk', '0007_risk_organization_risklog_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='risklog',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='inventory.inventory', verbose_name='Əlaqəli inventar'),
            preserve_default=False,
        ),
    ]
