# Generated by Django 5.0 on 2026-08-04 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('risk', '0008_risklog_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='inventory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='risks', to='inventory.inventory', verbose_name='Əlaqəli inventar'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='risklog',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='risk_logs', to='inventory.inventory', verbose_name='Əlaqəli inventar'),
        ),
    ]
