# Generated by Django 5.0 on 2026-08-04 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('risk', '0009_risk_inventory_alter_risklog_inventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risklog',
            name='inventory',
        ),
    ]
