# Generated by Django 5.0 on 2026-08-03 08:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryOwnerDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Departament adı')),
            ],
            options={
                'verbose_name': 'İnventar sahibi (departament)',
                'verbose_name_plural': 'İnventar sahibləri (departamentlər)',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='InventoryOwnerPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, unique=True, verbose_name='Ad Soyad')),
            ],
            options={
                'verbose_name': 'İnventar sahibi (şəxs)',
                'verbose_name_plural': 'İnventar sahibləri (şəxslər)',
                'ordering': ('full_name',),
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='Məhsulun adı')),
                ('inventory_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='İnventar nömrəsi')),
                ('owner_type', models.CharField(choices=[('person', 'Şəxs'), ('department', 'Departament'), ('aparat', 'Aparat (hamı üçün)')], max_length=20, verbose_name='Sahib növü')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son dəyişiklik tarixi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventories', to=settings.AUTH_USER_MODEL, verbose_name='Yaradan')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inventories', to=settings.AUTH_USER_MODEL, verbose_name='Son dəyişikliyi edən')),
                ('owner_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='inventory.inventoryownerdepartment', verbose_name='Sahib (departament)')),
                ('owner_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='inventory.inventoryownerperson', verbose_name='Sahib (şəxs)')),
            ],
            options={
                'verbose_name': 'İnventar',
                'verbose_name_plural': 'İnventarlar',
                'ordering': ('-created_at',),
            },
        ),
    ]
