# Generated by Django 5.0 on 2026-08-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='Son verilmiş nömrə')),
            ],
            options={
                'verbose_name': 'İnventar nömrə sayğacı',
                'verbose_name_plural': 'İnventar nömrə sayğacları',
            },
        ),
    ]
