# Generated by Django 5.0 on 2026-10-06 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_inventorynumbersequence"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="inventoryownerdepartment",
            options={
                "ordering": ("name",),
                "verbose_name": "İnventar sahibi (şöbə)",
                "verbose_name_plural": "İnventar sahibləri (şöbələr)",
            },
        ),
        migrations.AlterField(
            model_name="inventory",
            name="owner_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="inventories",
                to="inventory.inventoryownerdepartment",
                verbose_name="Sahib (şöbə)",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="owner_type",
            field=models.CharField(
                choices=[
                    ("person", "Şəxs"),
                    ("department", "Şöbə"),
                    ("aparat", "Aparat (hamı üçün)"),
                ],
                max_length=20,
                verbose_name="Sahib növü",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryownerdepartment",
            name="name",
            field=models.CharField(
                max_length=255, unique=True, verbose_name="Şöbənin adı"
            ),
        ),
    ]
