# Generated by Django 5.0 on 2026-07-15 07:30

import authentication.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('ip', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('fails', models.IntegerField(default=0)),
                ('locked', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Giriş cəhdi',
                'verbose_name_plural': 'Giriş cəhdləri',
            },
        ),
        migrations.CreateModel(
            name='PasswordReset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Elektron poçt')),
                ('token', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Şifrə yeniləməsi',
                'verbose_name_plural': 'Şifrə yeniləmələri',
            },
        ),
        migrations.CreateModel(
            name='SpecialPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Xüsusi icazə',
                'verbose_name_plural': 'Xüsusi icazələr',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Telefon nömrəsi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='user_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])], verbose_name='Şəkil')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='İstifadəçi adı')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='İstifadəçi emaili')),
                ('firstname', models.CharField(blank=True, default='', max_length=128, verbose_name='Adı')),
                ('lastname', models.CharField(blank=True, default='', max_length=128, verbose_name='Soyadı')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Doğum tarixi')),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=True)),
                ('join_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Qeydiyyat tarixi')),
                ('update_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Son düzəliş tarixi')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Kişi'), ('female', 'Qadın')], max_length=10, null=True, verbose_name='Cinsiyyət')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Istifadəçi',
                'verbose_name_plural': 'Istifadəçilər',
                'ordering': ('id',),
                'permissions': [('view_permissions_section', 'Can view permissions section in UserAdmin')],
            },
            managers=[
                ('objects', authentication.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='dəyişdirilmə tarixi')),
                ('title', models.CharField(max_length=255, verbose_name='Departamentin adı')),
                ('shortname', models.CharField(default='', max_length=255, verbose_name='Adın qısaltması')),
                ('order', models.PositiveIntegerField(default=2, verbose_name='Sıra')),
                ('unique_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='Departamentin unikal kodu')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='authentication.department')),
            ],
            options={
                'verbose_name': 'Departament',
                'verbose_name_plural': 'Departamentlər',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.department', verbose_name='Departament/Şöbə'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='dəyişdirilmə tarixi')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Vəzifə')),
                ('gpa_order', models.PositiveIntegerField(default=99, verbose_name='GPA-dakı Sıralama')),
                ('order', models.PositiveIntegerField(default=99, verbose_name='Sıralama')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='authentication.role')),
            ],
            options={
                'verbose_name': 'Vəzifə',
                'verbose_name_plural': 'Vəzifələr',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='authentication.role', verbose_name='Vəzifə'),
        ),
        migrations.AddField(
            model_name='user',
            name='special_permissions',
            field=models.ManyToManyField(blank=True, to='authentication.specialpermission', verbose_name='Xüsusi icazələr'),
        ),
    ]
