# Generated by Django 5.0 on 2026-07-24 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_fa_confirmed',
            field=models.BooleanField(default=False, verbose_name='2FA təsdiqlənib'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_fa_secret',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='2FA sirri'),
        ),
    ]
