# Generated by Django 5.0 on 2026-07-24 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_two_fa_confirmed_user_two_fa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Admin tərəfindən təsdiqlənib'),
        ),
    ]
