# Generated by Django 5.0 on 2026-07-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_organization_user_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_org_admin',
            field=models.BooleanField(default=False, help_text='Bu user öz qurumunun (organization sahəsində göstərilən) daxilində istifadəçiləri idarə edə, və qurumuna aid modul/alt-modullara hansı işçilərin çıxışı olacağını təyin edə bilər. Başqa qurumun datasına və ya user-lərinə çıxışı yoxdur.', verbose_name='Qurum admini'),
        ),
    ]
