# Generated by Django 5.0 on 2026-07-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_is_org_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='authorized_person_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Səlahiyyətli şəxsin adı'),
        ),
        migrations.AddField(
            model_name='organization',
            name='authorized_person_position',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Səlahiyyətli şəxsin vəzifəsi'),
        ),
        migrations.AddField(
            model_name='user',
            name='fin_kod',
            field=models.CharField(blank=True, max_length=7, null=True, verbose_name='FIN kod'),
        ),
    ]
