# Generated by Django 5.0 on 2026-08-05 06:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_organization_authorized_person_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoFABackupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='dəyişdirilmə tarixi')),
                ('code_hash', models.CharField(max_length=128)),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backup_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '2FA ehtiyat kodu',
                'verbose_name_plural': '2FA ehtiyat kodları',
            },
        ),
    ]
