# Generated by Django 5.0 on 2026-08-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_twofaresettoken_delete_twofabackupcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='is_manager_role',
            field=models.BooleanField(default=False, help_text='Bu vəzifədə olan istifadəçilər öz departamentlərindəki əməkdaşların icazə sorğularını görə və təsdiq/rədd edə bilər.', verbose_name='Şöbə rəhbəri səlahiyyəti'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_apparatus_head',
            field=models.BooleanField(default=False, help_text='Bu user öz qurumunun (organization) BÜTÜN əməkdaşlarının icazə sorğularını görə və HƏR KƏSİN (şöbə müdirləri daxil) sorğusunu təsdiq/rədd edə bilər. Özü icazə sorğusu yarada bilməz. Konkret vəzifə adından asılı deyil (Direktor, Aparat rəhbəri və s. ola bilər) - buna görə ayrıca sahədir.', verbose_name='Aparat rəhbəri'),
        ),
        migrations.DeleteModel(
            name='TwoFAResetToken',
        ),
    ]
