# Generated by Django 5.0 on 2026-08-07 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_role_is_manager_role_user_is_apparatus_head_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='gpa_order',
        ),
    ]
