# Generated by Django 5.0 on 2026-08-26 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_remove_role_gpa_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Bu departamentin aid olduğu qurum. Alt (child) departamentlər üçün bu sahə avtomatik olaraq valideyn departamentin qurumu ilə eyniləşdirilir.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='authentication.organization', verbose_name='Qurum'),
        ),
        migrations.AddField(
            model_name='role',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Bu vəzifənin aid olduğu departament (və dolayısı ilə qurum).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='authentication.department', verbose_name='Departament'),
        ),
    ]
