# Generated by Django 5.0 on 2026-09-16 06:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work_phone_number',
            field=models.CharField(blank=True, help_text='Ofis daxili nömrəsi (4 rəqəm), məs. 1234.', max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Daxili nömrə düz 4 rəqəmdən ibarət olmalıdır.')], verbose_name='İş telefonu (daxili)'),
        ),
    ]
