# Generated by Django 5.0 on 2026-10-06 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0013_user_work_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={
                "ordering": ["order"],
                "verbose_name": "Şöbə",
                "verbose_name_plural": "Şöbə və struktur bölmələr",
            },
        ),
        migrations.AlterField(
            model_name="department",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                help_text="Bu şöbənin aid olduğu qurum. Alt struktur bölmələr üçün bu sahə avtomatik olaraq valideyn şöbənin qurumu ilə eyniləşdirilir.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="departments",
                to="authentication.organization",
                verbose_name="Qurum",
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="title",
            field=models.CharField(
                max_length=255, verbose_name="Şöbənin / struktur bölmənin adı"
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="unique_code",
            field=models.CharField(
                blank=True, max_length=64, null=True, verbose_name="Şöbənin unikal kodu"
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="Bu vəzifənin aid olduğu şöbə (və dolayısı ilə qurum).",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="authentication.department",
                verbose_name="Şöbə",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="is_manager_role",
            field=models.BooleanField(
                default=False,
                help_text="Bu vəzifədə olan istifadəçilər öz şöbələrindəki əməkdaşların icazə sorğularını görə və təsdiq/rədd edə bilər.",
                verbose_name="Şöbə rəhbəri səlahiyyəti",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="authentication.department",
                verbose_name="Şöbə / struktur bölmə",
            ),
        ),
    ]
