# Generated by Django 5.0 on 2026-10-02 07:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0013_user_work_phone_number"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(verbose_name="Sual")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
            ],
            options={
                "verbose_name": "Quiz sualı",
                "verbose_name_plural": "Quiz sualları",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "correct_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Düzgün cavab sayı"
                    ),
                ),
                (
                    "total_count",
                    models.PositiveIntegerField(default=0, verbose_name="Sual sayı"),
                ),
                (
                    "percent",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Nəticə (%)"
                    ),
                ),
                ("passed", models.BooleanField(default=False, verbose_name="Keçdi")),
                (
                    "submitted_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Təsdiqlənmə tarixi",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_attempts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz nəticəsi",
                "verbose_name_plural": "Quiz nəticələri",
                "ordering": ("-submitted_at",),
            },
        ),
        migrations.CreateModel(
            name="QuizOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(max_length=500, verbose_name="Cavab variantı"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Düzgün cavabdır"),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Sıra")),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="trainings.quizquestion",
                        verbose_name="Sual",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cavab variantı",
                "verbose_name_plural": "Cavab variantları",
                "ordering": ("order", "id"),
            },
        ),
        migrations.CreateModel(
            name="QuizAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField(verbose_name="Sual")),
                (
                    "selected_text",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Seçilmiş cavab",
                    ),
                ),
                (
                    "correct_text",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=500,
                        verbose_name="Düzgün cavab",
                    ),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Düzgündür"),
                ),
                (
                    "attempt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="trainings.quizattempt",
                    ),
                ),
                (
                    "selected_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trainings.quizoption",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="trainings.quizquestion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Quiz cavabı",
                "verbose_name_plural": "Quiz cavabları",
                "ordering": ("id",),
            },
        ),
        migrations.CreateModel(
            name="Training",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Başlıq")),
                (
                    "description",
                    models.TextField(blank=True, default="", verbose_name="Təsvir"),
                ),
                (
                    "video",
                    models.FileField(
                        upload_to="trainings/videos/%Y/%m/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "mp4",
                                    "webm",
                                    "ogg",
                                    "ogv",
                                    "m4v",
                                    "mov",
                                ]
                            )
                        ],
                        verbose_name="Video",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="trainings/thumbnails/%Y/%m/",
                        verbose_name="Örtük şəkli",
                    ),
                ),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Yükləmə zamanı brauzer avtomatik təyin edir. Baxışın sona çatdığını yoxlamaq üçün istifadə olunur.",
                        verbose_name="Videonun müddəti (saniyə)",
                    ),
                ),
                (
                    "pass_percent",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="Quiz nəticəsi bu faizə bərabər və ya yuxarı olduqda 'keçdi' sayılır.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Keçid balı (%)",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Aktivdir"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Son dəyişiklik tarixi"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_trainings",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Yükləyən",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Boş buraxılsa, təlim BÜTÜN qurumların işçilərinə görünür.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trainings",
                        to="authentication.organization",
                        verbose_name="Qurum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Təlim materialı",
                "verbose_name_plural": "Təlim materialları",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddField(
            model_name="quizquestion",
            name="training",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_questions",
                to="trainings.training",
                verbose_name="Təlim",
            ),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="training",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_attempts",
                to="trainings.training",
                verbose_name="Təlim",
            ),
        ),
        migrations.CreateModel(
            name="TrainingFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Qiymət (1-5)",
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, default="", verbose_name="Rəy"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaradılma tarixi"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Son dəyişiklik tarixi"
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback",
                        to="trainings.training",
                        verbose_name="Təlim",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_feedback",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Təlim rəyi",
                "verbose_name_plural": "Təlim rəyləri",
                "ordering": ("-updated_at",),
            },
        ),
        migrations.CreateModel(
            name="TrainingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "Yarımçıq"),
                            ("completed", "Tam baxılıb"),
                        ],
                        default="in_progress",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "max_position",
                    models.FloatField(
                        default=0,
                        verbose_name="Cari sessiyada baxılan ən uzaq an (san.)",
                    ),
                ),
                (
                    "session_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Cari sessiyanın başlanğıcı"
                    ),
                ),
                (
                    "last_heartbeat_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Son aktivlik"
                    ),
                ),
                (
                    "attempts_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Baxışa başlama sayı"
                    ),
                ),
                (
                    "first_started_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="İlk baxış tarixi",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Tam baxılma tarixi"
                    ),
                ),
                (
                    "training",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_records",
                        to="trainings.training",
                        verbose_name="Təlim",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_progress",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="İstifadəçi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baxış qeydi",
                "verbose_name_plural": "Baxış qeydləri",
                "ordering": ("-last_heartbeat_at",),
            },
        ),
        migrations.AddConstraint(
            model_name="trainingfeedback",
            constraint=models.UniqueConstraint(
                fields=("user", "training"), name="uniq_training_feedback_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="trainingprogress",
            constraint=models.UniqueConstraint(
                fields=("user", "training"), name="uniq_training_progress_user"
            ),
        ),
    ]
