# Generated by Django 5.0 on 2026-09-15 11:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0012_alter_user_phone_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Circular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('serencam', 'Sərəncam'), ('ferman', 'Fərman'), ('daxili_qayda', 'Daxili qayda')], max_length=20, verbose_name='Növ')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('number', models.CharField(blank=True, default='', max_length=50, verbose_name='Nömrə')),
                ('document_date', models.DateField(blank=True, help_text='Sərəncam/fərmanın imzalandığı tarix.', null=True, verbose_name='Sənəd tarixi')),
                ('file', models.FileField(blank=True, null=True, upload_to='bulletin/circulars/%Y/%m/', verbose_name='Fayl (PDF və s.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son dəyişiklik tarixi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_circulars', to=settings.AUTH_USER_MODEL, verbose_name='Yaradan')),
                ('organization', models.ForeignKey(blank=True, help_text='Boş buraxılsa, bu sənəd BÜTÜN qurumların işçilərinə görünür.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='circulars', to='authentication.organization', verbose_name='Qurum')),
            ],
            options={
                'verbose_name': 'Sərəncam / Fərman / Daxili qayda',
                'verbose_name_plural': 'Sərəncamlar, Fərmanlar, Daxili qaydalar',
                'ordering': ('-document_date', '-created_at'),
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('summary', models.CharField(blank=True, default='', max_length=500, verbose_name='Qısa xülasə')),
                ('body', models.TextField(blank=True, default='', verbose_name='Mətn')),
                ('image', models.ImageField(blank=True, null=True, upload_to='bulletin/news/%Y/%m/', verbose_name='Şəkil')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Dərc tarixi')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son dəyişiklik tarixi')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_news', to=settings.AUTH_USER_MODEL, verbose_name='Yaradan')),
                ('organization', models.ForeignKey(blank=True, help_text='Boş buraxılsa, bu xəbər BÜTÜN qurumların işçilərinə görünür.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to='authentication.organization', verbose_name='Qurum')),
            ],
            options={
                'verbose_name': 'Xəbər',
                'verbose_name_plural': 'Xəbərlər',
                'ordering': ('-published_at',),
            },
        ),
    ]
