# Generated by Django 5.0 on 2026-09-16 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text='Kiçik hərflərlə, boşluqsuz (məs. ferman) - keçidlərdə istifadə olunur.', unique=True, verbose_name='Açar')),
                ('label', models.CharField(max_length=100, verbose_name='Ad')),
                ('plural_label', models.CharField(blank=True, default='', help_text='Boş buraxılsa, «Ad» sahəsi istifadə olunur.', max_length=100, verbose_name='Cəm forma')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='Qısa izah')),
                ('icon', models.CharField(choices=[('gavel', 'Ədalət çəkisi'), ('assignment', 'Tapşırıq'), ('rule', 'Qayda'), ('description', 'Sənəd'), ('article', 'Məqalə'), ('policy', 'Siyasət'), ('campaign', 'Elan'), ('event_note', 'Tədbir'), ('shield', 'Qalxan'), ('folder', 'Qovluq')], default='description', max_length=30, verbose_name='İkon')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıra')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktivdir')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son dəyişiklik tarixi')),
            ],
            options={
                'verbose_name': 'Sənəd kateqoriyası',
                'verbose_name_plural': 'Sənəd kateqoriyaları',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.AlterField(
            model_name='circular',
            name='category',
            field=models.ForeignKey(help_text="Kateqoriyalar 'Sənəd kateqoriyaları' bölməsindən idarə olunur.", on_delete=django.db.models.deletion.PROTECT, related_name='circulars', to='bulletin.bulletincategory', verbose_name='Növ'),
        ),
    ]
