# Generated by Django 5.0 on 2026-08-10 10:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0010_remove_role_gpa_order'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0007_alter_module_permitted_organizations_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='dəyişdirilmə tarixi')),
                ('operation_type', models.CharField(choices=[('crud', 'CRUD əməliyyatı'), ('approval', 'Təsdiq tələb edən əməliyyat')], max_length=16, verbose_name='Əməliyyat tipi')),
                ('action', models.CharField(choices=[('created', 'Yaratdı'), ('updated', 'Redaktə etdi'), ('deleted', 'Sildi'), ('exported', 'İxrac etdi'), ('requested', 'Sorğu göndərdi'), ('reviewed', 'Baxdı')], max_length=16, verbose_name='Hərəkət')),
                ('status', models.CharField(choices=[('completed', 'Tamamlandı'), ('pending', 'Gözləmədə'), ('in_progress', 'Baxılır'), ('approved', 'Təsdiqləndi'), ('rejected', 'Rədd edildi'), ('canceled', 'Ləğv edildi')], default='completed', max_length=16, verbose_name='Status')),
                ('category_code', models.CharField(blank=True, default='', max_length=100, verbose_name='Kateqoriya kodu')),
                ('category_title', models.CharField(blank=True, default='', max_length=150, verbose_name='Kateqoriya (Modul adı)')),
                ('user_username_snapshot', models.CharField(blank=True, default='', max_length=128, verbose_name='İstifadəçi adı (snapshot)')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Obyekt ID')),
                ('object_repr', models.CharField(blank=True, default='', max_length=255, verbose_name='Obyekt (snapshot)')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Təsvir')),
                ('changes', models.JSONField(blank=True, null=True, verbose_name='Dəyişikliklər')),
                ('total_steps', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mərhələ sayı')),
                ('current_step', models.PositiveSmallIntegerField(default=0, verbose_name='Hazırkı mərhələ')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP ünvanı')),
                ('user_agent', models.CharField(blank=True, default='', max_length=512, verbose_name='Brauzer/cihaz')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Obyekt tipi')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='core.module', verbose_name='Modul')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='authentication.organization', verbose_name='Qurum')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to=settings.AUTH_USER_MODEL, verbose_name='İstifadəçi')),
            ],
            options={
                'verbose_name': 'Əməliyyat',
                'verbose_name_plural': 'Əməliyyatlar',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OperationApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='dəyişdirilmə tarixi')),
                ('step_number', models.PositiveSmallIntegerField(verbose_name='Mərhələ nömrəsi')),
                ('role_label', models.CharField(blank=True, default='', max_length=150, verbose_name='Rol / vəzifə')),
                ('status', models.CharField(choices=[('pending', 'Gözləmədə'), ('approved', 'Təsdiqləndi'), ('rejected', 'Rədd edildi'), ('skipped', 'Keçildi')], default='pending', max_length=16, verbose_name='Status')),
                ('comment', models.TextField(blank=True, default='', verbose_name='Rəy / qeyd')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Baxılma tarixi')),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operation_approval_steps', to=settings.AUTH_USER_MODEL, verbose_name='Təyin olunan təsdiqləyici')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_steps', to='operations.operation', verbose_name='Əməliyyat')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_operation_steps', to=settings.AUTH_USER_MODEL, verbose_name='Baxan')),
            ],
            options={
                'verbose_name': 'Təsdiq mərhələsi',
                'verbose_name_plural': 'Təsdiq mərhələləri',
                'ordering': ('operation_id', 'step_number'),
            },
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['category_code', 'created_at'], name='operations__categor_0e4d51_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['status', 'created_at'], name='operations__status_aff964_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['user', 'created_at'], name='operations__user_id_107ebe_idx'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['content_type', 'object_id'], name='operations__content_cd29cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='operationapprovalstep',
            unique_together={('operation', 'step_number')},
        ),
    ]
