# Generated by Django 5.0 on 2026-10-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="status",
            field=models.CharField(
                choices=[
                    ("completed", "Tamamlandı"),
                    ("pending", "Gözləmədə"),
                    ("in_progress", "Baxılır"),
                    ("approved", "Təsdiqləndi"),
                    ("rejected", "İmtina edildi"),
                    ("canceled", "Ləğv edildi"),
                ],
                default="completed",
                max_length=16,
                verbose_name="Status",
            ),
        ),
        migrations.AlterField(
            model_name="operationapprovalstep",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Gözləmədə"),
                    ("approved", "Təsdiqləndi"),
                    ("rejected", "İmtina edildi"),
                    ("skipped", "Keçildi"),
                ],
                default="pending",
                max_length=16,
                verbose_name="Status",
            ),
        ),
    ]
