# Generated by Django 5.0 on 2026-08-07 07:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='yaradılma tarixi')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='dəyişdirilmə tarixi')),
                ('notification_type', models.CharField(choices=[('attendance_permission_new', 'Yeni icazə sorğusu'), ('attendance_permission_dept_approved', 'Şöbə müdiri təsdiqlədi'), ('attendance_permission_approved', 'İcazə təsdiqləndi'), ('attendance_permission_rejected', 'İcazə rədd edildi'), ('other', 'Digər')], default='other', max_length=64, verbose_name='Növü')),
                ('title', models.CharField(max_length=255, verbose_name='Başlıq')),
                ('body', models.CharField(blank=True, default='', max_length=500, verbose_name='Mətn')),
                ('link', models.CharField(blank=True, default='', max_length=255, verbose_name='Keçid')),
                ('related_app', models.CharField(blank=True, default='', max_length=64)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='Oxunub')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Oxunma tarixi')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Alıcı')),
            ],
            options={
                'verbose_name': 'Bildiriş',
                'verbose_name_plural': 'Bildirişlər',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='notificatio_recipie_4e3567_idx'), models.Index(fields=['recipient', 'created_at'], name='notificatio_recipie_f39341_idx')],
            },
        ),
    ]
