# Generated by Django 5.0 on 2026-10-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("attendance_permission_new", "Yeni icazə sorğusu"),
                    ("attendance_permission_dept_approved", "Şöbə müdiri təsdiqlədi"),
                    ("attendance_permission_approved", "İcazə təsdiqləndi"),
                    ("attendance_permission_rejected", "İcazədən imtina edildi"),
                    ("other", "Digər"),
                ],
                default="other",
                max_length=64,
                verbose_name="Növü",
            ),
        ),
    ]
